# Generated by Django 4.2.3 on 2024-01-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_unidadmedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la Unidad Medida', max_length=100, unique=True),
        ),
    ]
