# Generated by Django 4.2.3 on 2024-01-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_producto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
    ]
